'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { saveMember } from '@/lib/actions/members';
import { ImageUploader } from './ImageUploader';
import type { MemberInput } from '@/lib/validators/member';

export function MemberEditor({ id, initial }: { id?: string; initial?: MemberInput }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [error, setError] = useState(''); const [avatarUrl, setAvatarUrl] = useState(initial?.avatarUrl ?? '');
  return <form className="admin-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { const result = await saveMember({ slug: String(data.get('slug') ?? ''), nameVi: String(data.get('nameVi') ?? ''), nameEn: String(data.get('nameEn') ?? ''), roleVi: String(data.get('roleVi') ?? ''), roleEn: String(data.get('roleEn') ?? ''), bioVi: String(data.get('bioVi') ?? ''), bioEn: String(data.get('bioEn') ?? ''), linkedinUrl: String(data.get('linkedin') ?? ''), avatarUrl, isPublished: data.get('published') === 'on' }, id); if (result.ok) router.push('/admin/members'); else setError(result.message); }); }}><div className="form-panel"><p className="eyebrow">Member editor</p>{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="form-grid"><div className="form-field"><label htmlFor="member-name-vi">Name (VI)</label><input id="member-name-vi" name="nameVi" defaultValue={initial?.nameVi} required /></div><div className="form-field"><label htmlFor="member-name-en">Name (EN)</label><input id="member-name-en" name="nameEn" defaultValue={initial?.nameEn} required /></div></div><div className="form-grid"><div className="form-field"><label htmlFor="member-role-vi">Role (VI)</label><input id="member-role-vi" name="roleVi" defaultValue={initial?.roleVi} required /></div><div className="form-field"><label htmlFor="member-role-en">Role (EN)</label><input id="member-role-en" name="roleEn" defaultValue={initial?.roleEn} required /></div></div><div className="form-grid"><div className="form-field"><label htmlFor="member-slug">Slug</label><input id="member-slug" name="slug" defaultValue={initial?.slug} placeholder="your-name" required /></div><div className="form-field"><label htmlFor="member-linkedin">LinkedIn URL</label><input id="member-linkedin" name="linkedin" defaultValue={initial?.linkedinUrl} type="url" placeholder="https://linkedin.com/in/..." /></div></div><div className="form-grid"><div className="form-field"><label htmlFor="member-bio-vi">Bio (VI)</label><textarea id="member-bio-vi" name="bioVi" defaultValue={initial?.bioVi} rows={5} /></div><div className="form-field"><label htmlFor="member-bio-en">Bio (EN)</label><textarea id="member-bio-en" name="bioEn" defaultValue={initial?.bioEn} rows={5} /></div></div><div className="form-field"><ImageUploader bucket="member-media" onUploaded={setAvatarUrl} /><input type="hidden" name="avatarUrl" value={avatarUrl} /></div><label style={{ display: 'inline-flex', gap: 8, alignItems: 'center' }}><input type="checkbox" name="published" defaultChecked={initial?.isPublished} /> Published</label><div style={{ marginTop: 23 }}><button className="button button-primary" type="submit" disabled={pending}>{pending ? 'Saving...' : 'Save member'}</button></div></div></form>;
}
