'use client';

import Link from 'next/link';
import { ArrowDown, ArrowUp, ArrowUpRight, Pencil, Star, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState, useTransition } from 'react';
import { deleteProject, reorderProject, toggleProject } from '@/lib/actions/projects';
import type { ProjectView } from '@/types/view-models';

export function ProjectTable({ projects }: { projects: ProjectView[] }) {
  const router = useRouter(); const [search, setSearch] = useState(''); const [status, setStatus] = useState<'all' | 'published' | 'draft'>('all'); const [pending, startTransition] = useTransition();
  function run(action: Promise<{ ok: boolean }>) { startTransition(() => { void action.then(() => router.refresh()); }); }
  const rows = projects.filter((project) => `${project.title} ${project.slug}`.toLowerCase().includes(search.toLowerCase())).filter((project) => status === 'all' || (status === 'published' && project.isPublished) || (status === 'draft' && !project.isPublished));
  return <><div className="filter-row"><label className="sr-only" htmlFor="project-search">Search projects</label><input id="project-search" style={{ maxWidth: 260, minHeight: 36, border: '1px solid var(--line)', borderRadius: 999, padding: '0 13px', background: 'var(--surface)', color: 'var(--text)' }} placeholder="Search projects" value={search} onChange={(event) => setSearch(event.target.value)} /><label className="sr-only" htmlFor="project-status">Filter project status</label><select id="project-status" className="filter-link" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div><div className="admin-table-wrap"><table className="admin-table"><caption className="sr-only">Projects</caption><thead><tr><th>Project</th><th>Category</th><th>Year</th><th>Published</th><th>Featured</th><th>Order</th><th>Actions</th></tr></thead><tbody>{rows.map((project) => <tr key={project.id}><td><strong>{project.title}</strong><br /><span style={{ color: 'var(--muted)' }}>{project.slug}</span></td><td>{project.category?.name ?? '-'}</td><td>{project.year}</td><td><button className={`status-pill ${project.isPublished ? '' : 'draft'}`} type="button" disabled={pending} onClick={() => run(toggleProject(project.id, 'is_published', !project.isPublished))}>{project.isPublished ? 'Published' : 'Draft'}</button></td><td><button className="icon-button" type="button" disabled={pending} aria-label={`${project.isFeatured ? 'Remove' : 'Mark'} ${project.title} featured`} onClick={() => run(toggleProject(project.id, 'is_featured', !project.isFeatured))}><Star size={15} fill={project.isFeatured ? 'currentColor' : 'none'} /></button></td><td><button className="icon-button" type="button" disabled={pending} aria-label={`Move ${project.title} up`} onClick={() => run(reorderProject(project.id, 'up'))}><ArrowUp size={14} /></button><button className="icon-button" type="button" disabled={pending} aria-label={`Move ${project.title} down`} onClick={() => run(reorderProject(project.id, 'down'))}><ArrowDown size={14} /></button></td><td><div className="admin-actions"><Link className="button" href={`/admin/projects/${project.id}`} aria-label={`Edit ${project.title}`}><Pencil size={14} /></Link><Link className="button" href={`/${project.locale}/projects/${project.slug}`} target="_blank" aria-label={`Open ${project.title}`}><ArrowUpRight size={14} /></Link><button className="button" type="button" disabled={pending} aria-label={`Delete ${project.title}`} onClick={() => { if (window.confirm('Delete this project?')) run(deleteProject(project.id)); }}><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div></>;
}
